version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: nest-api
    command:
      - sh
      - -c
      - |
        npm install
        npx prisma migrate dev
        npm run start:dev
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database
    volumes:
      - .:/usr/node/app:rw
      - ./node_modules:/usr/node/app/node_modules:rw
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: gazin-tech

  database:
    image: postgres:13
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: gazin-tech
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  postgres:
